search: false
backend:
  name: github
  repo: ShadowCHuyna/blog
  branch: main
  base_url: "https://auth.potatom.ru"

media_folder: "assets/images"
public_folder: "/assets/images"
site_url: https://potatom.ru
display_url: https://potatom.ru

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}